### ISSUE TITLE
Requesting access to dataset. 

### ISSUE THREAD

**Issue by skwolvie** [raosudha89/GYAFC-corpus#2]
Dear author's,
I have got access to Yahoo's L6 dataset, and I have forwarded the acknowledgment, and written multiple times to the designated email address requesting access to the GYFAC-corpus. My requests have been unanswered for quite some time. Please let me know if there is any other way to access this dataset. 

I look forward to gaining access to this incredible piece of work.

**Comment by skwolvie** [comment]
Is there any other way to reach out and get access to the data? I believe the email inbox is not monitored. I have been constantly sending out multiple emails but I hear no response. 

Please help!

**Comment by xyiiinexg3** [comment]
Excuse me, I have a question about the dataset require ([L6 - Yahoo! Answers Comprehensive Questions and Answers version 1.0 (multi part)](https://webscope.sandbox.yahoo.com/catalog.php?datatype=l&did=11)). Could you tell me how to get access to this dataset?
T^T!!help!!
![image](https://github.com/luofuli/DualRL/assets/65646825/5bea2f4f-9330-4e35-9075-1212a695d904)
![image](https://github.com/luofuli/DualRL/assets/65646825/a19fd44d-3fab-4b42-9b02-17a3c45c09c5)
