### ISSUE TITLE
How to access the data?

### ISSUE THREAD

**Issue by skwolvie** [raosudha89/GYAFC-corpus#3]
I believe the inbox of the email address mentioned here is not monitored. I have been constantly sending out multiple emails but I hear no response. 

Please help!

**Comment by thangld201** [comment]
@raosudha89 Could you please check the email ? I have sent the request with L6 data approval from Yahoo.

**Comment by raosudha89** [comment]
What is your email address? I can't find any email from you in my inbox.
Can you send it again to ***@***.***? Thanks.

**Comment by thangld201** [comment]
@raosudha89 I have re-sent an email to addresses: tetreaul@gmail.com and raosudha@cs.umd.edu. Could you please confirm if you have received it ?

**Comment by raosudha89** [comment]
I have not received any email. If you could re-send it to
***@***.*** that would be great. Thanks.

**Comment by thangld201** [comment]
@raosudha89 So both of the emails I included (tetreaul@gmail.com, raosudha@cs.umd.edu) do not work then ? My email is [thangld.bkhn@gmail.com](sendtothangld.bkhn@gmail.com) and I have sent to both of those emails. Do you mean to send it to another email ? I only see your reply as 

` If you could re-send it to ***@***.*** that would be great.`

 , so I am not sure which address you are refering to.

**Comment by thangld201** [comment]
@raosudha89 Could you please confirm which email `***@***.***` is ? And also the spam inbox as well (I'm afraid it might have gone here) ?

EDIT: I have sent one to sudhra@microsoft.com, I hope this is correct.
