### ISSUE TITLE
Access requests unanswered

### ISSUE THREAD

**Issue by sztal** [raosudha89/GYAFC-corpus#4]
Dear GYAFC Team,

I sent a request to gain access to the GYAFC dataset some time ago (I already obtained access to L6 corpus from Yahoo!). However, I still have not receive any response.

Is the GYAFC corpus still available for research?

**Comment by alin-shen** [comment]
> Dear GYAFC Team,
> 
> I sent a request to gain access to the GYAFC dataset some time ago (I already obtained access to L6 corpus from Yahoo!). However, I still have not receive any response.
> 
> Is the GYAFC corpus still available for research?

Sorry to bother you, did you get the response?

**Comment by sztal** [comment]
Yes, I was contacteed via email some time after opening the ticket, so I am closing it. Thanks a lot!

**Comment by alin-shen** [comment]
您好，我是申琳。您的邮件我已收到，我会在详细阅读后尽快回复您，谢谢。
